## Dataset and Preprocessing

TODO: Provide information about the datasets (e.g., where to download them, what
are the variables in there) and also explain how you preprocess the data.

After settling on the topic of Schiphol, we started searching for our datasets. The [first dataset](https://www.schiphol.nl/nl/schiphol-group/pagina/verkeer-en-vervoer-cijfers/), provided by Schiphol, contains information about the monthly traffic at Schiphol since January 1992. Finding a second dataset was more challenging than expected. Many of the RIVM datasets were provided in `.rdf` format and contained insufficient data or were unable to be read at all. We then stumbled upon a dataset containing the emission of fine particulate matter as measured from eight measuring points around Schiphol. Although this dataset was exactly what we were looking for, it only contained data from 2017 and 2018. Having not found an alternative, we used this dataset for the project proposal. After the proposal, we found a [third dataset](https://www.emissieregistratie.nl/data/vliegvelden), provided by the 'Rijksoverheid', containing the emission of a number of substances from 1990 till 2022 at different airports in the Netherlands. The first and third datasets were used for the final deliverable.

### Cleaning

All the datasets came in `.xlsx` format and were adjusted to `.csv` to be further processed using the Pyhton pandas library. 

The first dataset, containing Schiphol airport's monthly traffic data, was cleaned first. Initially, we removed all unnamed columns and rows that only served a visual purpose in the original .xlsx file. We also ensured that all string types were converted to float types where necessary. Next, we decided to save the total yearly data instead of the total monthly data. This decision was made because the second dataset also presented its information per year.

The second dataset contained the emission data for all airports in the Netherlands, with 12 columns and 40,316 rows, of which only 2,960 rows contained information about Schiphol airport. We isolated these rows and saved them in a new dataframe. To further clean up the dataset, we dropped irrelevant columns.

### Variables

The variables in the first and second dataset can be classified under:

- Continuous / Ratio variables:
`Year`
`Air_Transport_Movements_Europe`
`Air_Transport_Movements_Intercontinental`
`Air_Transport_Movements_Total`
`Passengers_Europe`
`Passengers_Intercontinental`
`Passengers_Total*`
`Passengers_O&D`
`Passengers_Transfer`
`Passengers_Total*.1`
`Passengers_Scheduled`
`Passengers_Non Scheduled`
`Passengers_Transit direct`
`Passengers_Total`
`Cargo (tonnes)`
`Mail (tonnes)`
`EMISSIE (kg)`

- Discrete / Ordinal variables: None in the given datasets.

- Discrete / Nominal variables:
`VLIEGVELD`
`VLIEGVELD_CODE`
`STOFNAAM`
`STOF_CODE`
`COMPARTIMENT`
`COMPARTIMENT_CODE`
`EMISSIEOORZAAK`
`EMISSIEOORZAAK_CODE`

- Discrete / Interval variables: None in the given datasets.

- Discrete / Ratio variables: None in the given datasets.

In [2]:
import pandas as pd

In [6]:
# Load the cleaned Schiphol Traffic dataset

df = pd.read_csv("../notebooks/cache/Traffic_Data_Cleaned.csv")
df

# https://www.schiphol.nl/nl/schiphol-group/pagina/verkeer-en-vervoer-cijfers/

,Year,Month,Air_Transport_Movements_Europe,Air_Transport_Movements_Intercontinental,Total_Air_Transport_Movements,Passengers_Europe,Passengers_Intercontinental,Passengers_Total*,Passengers_O&D,Passengers_Transfer,Passengers_Total*.1,Passengers_Scheduled,Passengers_Non_Scheduled,Passengers_Transit_direct,Passengers_Total,Cargo (tonnes),Mail (tonnes)
0,1992,January,14.716,2.955,17.671,726.163,423.659,1.149.822,739.774,410.048,1.149.822,1.051.816,98.006,35.052,1.184.874,50.457,2.166
1,NaN,February,14.030,2.779,16.809,719.055,367.924,1.086.979,728.823,358.156,1.086.979,997.218,89.761,30.491,1.117.470,56.180,2.154
2,NaN,March,15.454,2.998,18.452,847.487,429.187,1.276.674,866.246,410.428,1.276.674,1.160.363,116.311,32.161,1.308.835,64.284,2.242
3,NaN,April,16.649,3.011,19.660,1.056.108,466.414,1.522.522,1.065.468,457.054,1.522.522,1.307.113,215.409,32.640,1.555.162,56.924,2.252
4,NaN,May,17.591,3.167,20.758,1.223.278,518.839,1.742.117,1.276.443,465.674,1.742.117,1.411.578,330.539,34.620,1.776.737,58.328,2.232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Load the cleaned yearly SchipholTtraffic dataset

df_yearly = pd.read_csv("../notebooks/cache/Yearly_Traffic_Data_Cleaned.csv")
df_yearly

,Year,Air_Transport_Movements_Europe,Air_Transport_Movements_Intercontinental,Air_Transport_Movements_Total,Passengers_Europe,Passengers_Intercontinental,Passengers_Total*,Passengers_O&D,Passengers_Transfer,Passengers_Total*.1,Passengers_Scheduled,Passengers_Non Scheduled,Passengers_Transit direct,Passengers_Total,Cargo (tonnes),Mail (tonnes)
0,1992,200566.0,38246.0,238812.0,12628221.0,6084369.0,18712590.0,12965174.0,5747416.0,18712590.0,15618006.0,3094584.0,432474.0,19145064.0,695040.0,28799.0
1,1993,216872.0,42803.0,259675.0,13884524.0,6885688.0,20770212.0,13094576.0,7675636.0,20770212.0,17715938.0,3054274.0,504057.0,21274269.0,775378.0,33589.0
2,1994,228163.0,45901.0,274064.0,15357944.0,7711763.0,23069707.0,14410593.0,8659114.0,23069707.0,19883172.0,3186535.0,490091.0,23559798.0,837904.0,36574.0
3,1995,239275.0,51415.0,290690.0,16248508.0,8608198.0,24856706.0,15231696.0,9625010.0,24856706.0,21480170.0,3376536.0,498295.0,25355001.0,977531.0,41784.0
4,1996,265804.0,55976.0,321780.0,17671327.0,9590717.0,27262044.0,16312216.0,10949828.0,27262044.0,23789314.0,3472730.0,532837.0,27794881.0,1082846.0,41806.0
5,1997,290064.0,59412.0,349476.0,20389033.0,10631969.0,31021002.0,17929440.0,13091562.0,31021002.0,27304883.0,3716119.0,548975.0,31569977.0,1161234.0,46048.0
6,1998,314549.0,62261.0,376810.0,22626274.0,11325874.0,33952148.0,19608768.0,14343380.0,33952148.0,29956021.0,3996127.0,467995.0,34420143.0,1171256.0,4749.0
7,1999,329684.0,63922.0,393606.0,24282534.0,12142579.0,36425113.0,20950665.0,15474448.0,36425113.0,32099376.0,4325737.0,346902.0,36772015.0,1180717.0,44567.0
8,2000,348720.0,66208.0,414928.0,26360776.0,12909834.0,39270610.0,22723260.0,16547350.0,39270610.0,34496436.0,4774174.0,336315.0,39606925.0,1222594.0,44792.0
9,2001,348697.0,67765.0,416462.0,26801533.0,12507908.0,39309441.0,23284957.0,16024484.0,39309441.0,34597071.0,4712370.0,221682.0,39531123.0,1183208.0,50953.0
10,2002,332570.0,68815.0,401385.0,28054623.0,12532939.0,40587562.0,23580736.0,17006826.0,40587562.0,36102477.0,4485085.0,148447.0,40736009.0,1239900.0,48726.0
11,2003,321948.0,71049.0,392997.0,27701903.0,12106746.0,39808649.0,23466695.0,16341954.0,39808649.0,35589774.0,4218875.0,151751.0,39960400.0,1306155.0,47605.0
12,2004,325703.0,77035.0,402738.0,28959662.0,13465730.0,42425392.0,24457204.0,17968188.0,42425392.0,38034588.0,4390804.0,115788.0,42541180.0,1421023.0,46181.0
13,2005,324307.0,80512.0,404819.0,29746153.0,14331061.0,44077214.0,25412926.0,18664288.0,44077214.0,39933756.0,4143458.0,79791.0,44157005.0,1449795.0,46064.0
14,2006,342101.0,81174.0,423275.0,31286807.0,14700740.0,45987547.0,26861539.0,19126008.0,45987547.0,42278322.0,3709225.0,78918.0,46066465.0,1526502.0,40321.0
15,2007,352933.0,83157.0,436090.0,32517044.0,15227858.0,47744902.0,28014342.0,19730560.0,47744902.0,44507405.0,3237497.0,50246.0,47795148.0,1610282.0,41103.0
16,2008,342700.0,85952.0,428652.0,31725823.0,15666116.0,47391939.0,27071867.0,20320072.0,47391939.0,43789656.0,3602283.0,38173.0,47430112.0,1567712.0,34873.0
17,2009,313383.0,77986.0,391369.0,28990473.0,14532639.0,43523112.0,24668806.0,18854306.0,43523112.0,39983690.0,3539422.0,4726.0,43570372.0,1286372.0,30749.0
18,2010,304533.0,81855.0,386388.0,29772346.0,15364621.0,45136967.0,26390347.0,18746620.0,45136967.0,42122863.0,3014104.0,74782.0,45211749.0,1512256.0,25878.0
19,2011,336169.0,8418.0,420349.0,33825310.0,15855315.0,49680625.0,29491315.0,20189310.0,49680625.0,47152347.0,2528278.0,74627.0,49755252.0,1523806.0,2588.0
20,2012,340198.0,83255.0,423453.0,34647266.0,16328326.0,50975592.0,30100632.0,20874960.0,50975592.0,48240587.0,2735005.0,59998.0,51035590.0,1483448.0,28375.0
21,2013,341385.0,84199.0,425584.0,35671436.0,16856263.0,52527699.0,30515701.0,22011998.0,52527699.0,49818536.0,2709163.0,41501.0,52569200.0,1531089.0,34872.0
22,2014,353786.0,8451.0,438296.0,37903464.0,17037070.0,54940534.0,32665136.0,22275398.0,54940534.0,52233152.0,2707382.0,37489.0,54978023.0,1633195.0,37481.0
23,2015,364602.0,86077.0,450679.0,40683215.0,17562330.0,58245545.0,35212953.0,23032592.0,58245545.0,55977282.0,2268263.0,39319.0,58284864.0,1620970.0,34385.0
24,2016,390228.0,88635.0,478863.0,45121520.0,18412190.0,63533710.0,39497377.0,24036333.0,63533710.0,62032189.0,1501521.0,91824.0,63625534.0,1666360.0,32447.0
25,2017,404768.0,91972.0,496740.0,48649342.0,19751804.0,68401146.0,43086344.0,25314802.0,68401146.0,66225540.0,2175606.0,114279.0,68515425.0,1761060.0,25811.0
26,2018,406249.0,93195.0,499444.0,49979656.0,20976938.0,70956594.0,44992618.0,25964126.0,70956594.0,69403648.0,1552946.0,96553.0,71053147.0,1716497.0,21486.0
27,2019,404624.0,92202.0,496826.0,50542973.0,21137361.0,71680334.0,45807812.0,25872522.0,71680334.0,71092189.0,588145.0,26665.0,71706999.0,1443885.0,19622.0
28,2020,172356.0,54948.0,227304.0,15122741.0,5758723.0,20881464.0,12096950.0,8784514.0,20881464.0,20759567.0,121897.0,258.0,20884044.0,1441521.0,14831.0
29,2021,205300.0,61667.0,266967.0,18981096.0,6509728.0,25490824.0,14362224.0,11128600.0,25490824.0,25319213.0,171611.0,1809.0,25492633.0,1667304.0,1355.0
30,2022,321679.0,75967.0,397646.0,37138923.0,15331957.0,52470880.0,33217553.0,19253327.0,52470880.0,51683556.0,787324.0,1308.0,52472188.0,1437812.0,7715.0
31,2023,357568.0,84401.0,441969.0,43339518.0,18548110.0,61887628.0,39431773.0,22455853.0,61887628.0,61078007.0,809621.0,1958.0,61889586.0,1378041.0,5898.0
32,2024,119307.0,2821.0,147517.0,13866634.0,6000294.0,19866928.0,12234469.0,7632459.0,19866928.0,19677962.0,188966.0,4510.0,19867379.0,494256.0,2152.0

In [5]:
# Load the cleaned Schiphol Emissie dataset

df_emission = pd.read_csv("../notebooks/cache/Schiphol_Emissie_Cleaned.csv")
df_emission

# https://www.emissieregistratie.nl/data/vliegvelden

,EMISSIEJAAR,VLIEGVELD,VLIEGVELD_CODE,STOFNAAM,STOF_CODE,COMPARTIMENT,COMPARTIMENT_CODE,EMISSIEOORZAAK,EMISSIEOORZAAK_CODE,EMISSIE (kg)
0,1990,Vliegveld Luchthaven Schiphol,220801,Anthraceen,535,Lucht,10,"Vliegverkeer, APU",930005,"0,010647538"
1,1990,Vliegveld Luchthaven Schiphol,220801,Benzeen,515,Lucht,10,"Vliegverkeer, APU",930005,"109,275126"
2,1990,Vliegveld Luchthaven Schiphol,220801,Benzo(a)Pyreen,539,Lucht,10,"Vliegverkeer, APU",930005,"0,003642579"
3,1990,Vliegveld Luchthaven Schiphol,220801,Benzo(b)Fluorantheen,540,Lucht,10,"Vliegverkeer, APU",930005,"0,007285158"
4,1990,Vliegveld Luchthaven Schiphol,220801,Benzo(k)Fluorantheen,541,Lucht,10,"Vliegverkeer, APU",930005,"0,001905349"
...,...,...,...,...,...,...,...,...,...,...
2955,2022,Vliegveld Luchthaven Schiphol,220801,Loodverb. (als Pb),111,Lucht,10,"Vliegverkeer, Remslijtage",930009,"2,177753808"
2956,2022,Vliegveld Luchthaven Schiphol,220801,Nikkelverb. (als Ni),114,Lucht,10,"Vliegverkeer, Remslijtage",930009,"5,008833758"
2957,2022,Vliegveld Luchthaven Schiphol,220801,TSP (Totaal stof),999,Lucht,10,"Vliegverkeer, Remslijtage",930009,"5444,384519"
2958,2022,Vliegveld Luchthaven Schiphol,220801,Zinkverb. (als Zn),120,Lucht,10,"Vliegverkeer, Remslijtage",930009,"81,66576779"
2959,2022,Vliegveld Luchthaven Schiphol,220801,Zwavel,140,Lucht,10,"Vliegverkeer, Remslijtage",930009,"54,44384519"